PingCAP-QE/jenkins-templates

- atom-jobs/atom-build.groovy
Added: https://ci.pingcap.net/job/cache-code/
> Add atom build

- atom-jobs/cache-code.groovy
* cache code for ci，upload code with specific commit id to file-server
* current support: pr id + commit id / branch name + commit id
> atom job: cache code upload to file-server

- atom-jobs/build-common.groovy
- atom-jobs/docker-common.groovy
> add tiem support

- atom-jobs/build-common.groovy
> change tiem go version

- atom-jobs/docker-common.groovy
tiem maintain dockerfile in their repo
> tiem maintain dockerfile in their repo

- pipelines/release-one-image-by-branch.groovy
- add script to release one image
> add script to release one image

- atom-jobs/atom-cyclo.groovy
- pipelines/pr-verify-check.groovy
* add atom-job to statistics circle complexity
> add atom-cyclo task

- atom-jobs/atom-cyclo.groovy
* make cyclo test not block ci
> cyclo alway true, not block ci

- atom-jobs/atom-gosec.groovy
- pipelines/pr-verify-check.groovy
> atom-job: add gosec step

- pipelines/release-one-image-by-branch.groovy
- change branch to build tiem image
> change branch to build tiem image

- pipelines/pr-verify-check.groovy
> reformat yaml

- atom-jobs/atom-common.groovy
- pipelines/pr-verify-check.groovy
> add common task type

- pipelines/pr-verify-check.groovy
> fix spell error

- pipelines/pr-verify-check.groovy
> fix common task bug

- atom-jobs/cache-code.groovy
- pipelines/pr-verify-check.groovy
- pipelines/pre-release-docker.groovy
> support docs cn build

- atom-jobs/atom-common.groovy
- pipelines/pr-verify-check.groovy
> add target branch env

- atom-jobs/cache-code.groovy
- pipelines/pr-verify-check.groovy
* support any repo code cache instead of hardcode repo array
> cache code: support any code cache

- atom-jobs/atom-build.groovy
- atom-jobs/atom-common.groovy
- atom-jobs/atom-cyclo.groovy
- atom-jobs/atom-gosec.groovy
- atom-jobs/atom-lint.groovy
- atom-jobs/atom-ut.groovy
> add uuid for atom job

- pipelines/pr-verify-check.groovy
* print triggered job link from some  build job not display link on blue  ocean
> schedule: print triggered job link

- pipelines/pr-verify-check.groovy
Reverts PingCAP-QE/jenkins-templates#26
> Revert "schedule: print triggered job link"

- atom-jobs/build-common.groovy
- clean workspace before build for CD build
> clean workspace before build

- atom-jobs/atom-common.groovy
- pipelines/common.groovy
- pipelines/merge-check.groovy
- pipelines/pr-verify-check.groovy
- add merge ci step
- refactor common function
> add merge ci step

- pipelines/pr-verify-check.groovy
> remove duplicate script

- pipelines/merge-check.groovy
- fix update commit status no vars
> fix update commit status no vars

- atom-jobs/build-common.groovy
> cache code: add nfs cache

- atom-jobs/atom-ut.groovy
* disable pod resouce limit for dm ut need more memory to pass
> atom-ut: temp disable pod resource limit

- pipelines/release-all-images-by-branch.groovy
> update build tag

- atom-jobs/atom-lint.groovy
> fix lint report collection

- atom-jobs/atom-common.groovy
- atom-jobs/atom-cyclo.groovy
- atom-jobs/atom-gosec.groovy
- atom-jobs/atom-lint.groovy
- atom-jobs/atom-ut.groovy
- atom-jobs/cache-code.groovy
* get summary info of task run result
> atom-job: summary task result

- atom-jobs/atom-build.groovy
- atom-jobs/atom-common.groovy
- atom-jobs/atom-cyclo.groovy
- atom-jobs/atom-gosec.groovy
- atom-jobs/atom-lint.groovy
- atom-jobs/atom-ut.groovy
- pipelines/common.groovy
- pipelines/daily-check.groovy
- pipelines/merge-check.groovy
- pipelines/pr-verify-check.groovy
add extra params for data collection
> add extra params for data collection

- pipelines/release-all-images-by-branch.groovy
* add release-5.3 to cron trigger
> Add crontab build for release-5.3

- pipelines/pre-release-docker.groovy
- pipelines/release-all-images-by-branch.groovy
> fix: fix bug build one more image

- pipelines/daily-check.groovy
- pipelines/merge-check.groovy
- pipelines/pr-verify-check.groovy
> fix sub task name

- pipelines/common.groovy
* displace blueocean url to see task detail
> atom: display more task result to blueocean

- atom-jobs/atom-cyclo.groovy
- atom-jobs/atom-gosec.groovy
This PR is used to fix the reported branch when collecting data from atom jobs, as PR https://github.com/PingCAP-QE/jenkins-templates/pull/45 added few more param.
> Fix branch when collecting data from atom jobs

- atom-jobs/atom-ut.groovy
- pipelines/common.groovy
* atom-ut support secret token
> atom-ut support token

- atom-jobs/docker-common.groovy
fix multi docker builds on one node
> fix multi docker builds on one node

- pipelines/pr-verify-check.groovy
* get sub task rsults, if pipeline fail then send feishu message
> get tasks results

- pipelines/pr-verify-check.groovy
related to https://ci.pingcap.net/blue/organizations/jenkins/docs-verify-ci/detail/docs-verify-ci/1956/pipeline
* fix env variable error
> fix: RUN_DISPLAY_URL env

- atom-jobs/build-common.groovy
- pipelines/release-all-images-by-branch.groovy
> add failpoint image for br

- atom-jobs/atom-ut.groovy
> ci: fix go get timeout

- atom-jobs/atom-ut.groovy
> temp remove go cache

- atom-jobs/atom-lint.groovy
> fix lint cache error

- atom-jobs/patch-common.groovy
Everytime we build tiup patch, need manuel to remove bin dir and then upload to fileserver. it need to be done by every hotfix
This pr add an automation  job that will triggered by multi branch jobs
> Add patch tiup binary

- atom-jobs/atom-build.groovy
- pipelines/common.groovy
* to support self defined image from config
> atom build: support self defined image

- pipelines/tcms-daily-reports.groovy
> add tcms daily ci pipeline

- pipelines/common.groovy
> fix: fix class error

- atom-jobs/atom-lint.groovy
> reduce lint job quota

- atom-jobs/atom-tcms.groovy
> fix script spell

- pipelines/daily-check.groovy
> fix: fix env RUN_DISPLAY_URL

- atom-jobs/atom-jenkins-it-trigger.groovy
* fix failed atom jenkins task
> fix: fix daily ci

- atom-jobs/build-common.groovy
* build common to support hotfix branch
> feat: support hotfix branch

- atom-jobs/atom-cyclo.groovy
- atom-jobs/atom-gosec.groovy
- atom-jobs/atom-lint.groovy
- atom-jobs/atom-tcms.groovy
- atom-jobs/atom-ut.groovy
This PR will add additional param `{$env.BUILD_URL}` for all atom jobs.
> Add BUILD_URL env for agents

- atom-jobs/atom-lint.groovy
> fix: catch tiinsight exception

- atom-jobs/atom-lint.groovy
Reverts PingCAP-QE/jenkins-templates#79
> Revert "fix: catch tiinsight exception"

- atom-jobs/atom-jenkins-it-trigger.groovy
* save some it test result to json file
> atom-jenkins-it: save result to json

- atom-jobs/atom-ut-codecov.groovy
- pipelines/common.groovy
- pipelines/daily-check.groovy
* add atom-ut-codecov for same coverage against tidb_ghpr_coverage
> add atom codecov

- atom-jobs/atom-ut-codecov.groovy
* add variable lines_coverage_rate
> fix: add variable lines_coverage_rate

- pipelines/pre-release-docker.groovy
Signed-off-by: Qiang Zhou <zhouqiang.cl@gmail.com>
> add ng monitoring image

- atom-jobs/atom-ut-codecov.groovy
> fix: fix ut repot path

- atom-jobs/build-common.groovy
* build-common support param NEED_SOURCE_CODE
> feat: build-common support param NEED_SOURCE_CODE

- atom-jobs/build-common.groovy
> fix: fix properities error

- atom-jobs/atom-build.groovy
- atom-jobs/atom-jenkins-it-trigger.groovy
- atom-jobs/atom-lint.groovy
* build and lint add some result info
> fix br cdc json stackoverflow

- atom-jobs/build-common.groovy
> fix jenkins params no use

- atom-jobs/build-common.groovy
ref to https://github.com/PingCAP-QE/ci/pull/565
> Remove test dir on plugin

- atom-jobs/atom-build.groovy
> do not use nfs for mod cache

- pipelines/release-all-images-by-branch.groovy
Signed-off-by: Qiang Zhou <zhouqiang.cl@gmail.com>
> fix dumpling

- atom-jobs/build-common.groovy
- atom-jobs/docker-common.groovy
Signed-off-by: Schrodinger ZHU Yifan <i@zhuyi.fan>
> adjust TiFlash pipelines

- atom-jobs/build-common.groovy
Signed-off-by: Schrodinger ZHU Yifan <i@zhuyi.fan>
> fix TiFlash darwin build

- atom-jobs/build-common.groovy
Signed-off-by: Schrodinger ZHU Yifan <i@zhuyi.fan>
> switch arm darwin build node for tiflash

- atom-jobs/docker-common.groovy
> compatibility to tiflash

- atom-jobs/cache-code.groovy
> fix: make cache-code pod label unique

- atom-jobs/cache-code.groovy
> cache-code: sleep 10s for tar dir error

- atom-jobs/build-common.groovy
Signed-off-by: Qiang Zhou <zhouqiang.cl@gmail.com>
> fix importer build

- atom-jobs/build-common.groovy
> add token for monitor build

- pipelines/pre-release-docker.groovy
Signed-off-by: Qiang Zhou <zhouqiang.cl@gmail.com>
> add release-5.1 arm build

- atom-jobs/build-common.groovy
* try download cache code from fileserver
* fix tics submodule update failed in mac
* increase submodule timeout from default 10min to 30min
> build-common: try download cachecode from fileserver

- atom-jobs/build-common.groovy
* not auto create pr on pingcap/monitoring
* fix clone timeout
> not auto create pr on repo pingcap/monitoring

- atom-jobs/build-common.groovy
* build-common support dm (version >= 5.3.0)
> build common support dm

- atom-jobs/build-common.groovy
See https://github.com/PingCAP-QE/ci/pull/796.
> *: always use gcc 8

- atom-jobs/build-common.groovy
- pipelines/release-all-images-by-branch.groovy
* some repo support multiarch image: tidb / pd / tikv
> support qa multiarch

- pipelines/release-all-images-by-branch.groovy
> fix some error

- atom-jobs/build-common.groovy
- support update go version to 1.18
> [WIP] support update go version to 1.18

- pipelines/release-all-images-by-branch.groovy
> add release-6.0 branch

- pipelines/release-all-images-by-branch.groovy
update nightly version to v6.1.0-nighlty
> update nightly version to v6.1.0-nighlty

- pipelines/release-all-images-by-branch.groovy
> fix multiarch build image

- atom-jobs/build-common.groovy
plugin build need tidb, fix tidb clone timeout
> fix clone tidb timeout

- atom-jobs/build-common.groovy
replay test ci https://cd.pingcap.net/blue/organizations/jenkins/build-common/detail/build-common/86861/pipeline
> plugin need package

- pipelines/release-all-images-by-branch.groovy
> fix arm monitor image

- pipelines/check-all-images-by-trivy.groovy
- use trivy to check release image
> use trivy to check release image

- tipipeline/checkers/tcms-plans-check.groovy
> support trigger tmcs by plan

- atom-jobs/atom-gosec.groovy
* upgrade vesion to fix v2.9.1 error on go1.18
> upgrade gosec version

- tipipeline/checkers/tcms-check.groovy
- tipipeline/checkers/tcms-plans-check.groovy
add token for every tcms request
> add token for every tcms request

- atom-jobs/build-common.groovy
* user arm k8s pod to build tidb and plugin
> tidb and plugin use arm k8s pod build

- atom-jobs/build-common.groovy
* upgrade go version from go 1.18 to 1.18.2
> go 1.18 use go1.18.2

- pipelines/release-all-binary-by-branch.groovy
- pipelines/release-all-images-by-branch.groovy
- pipelines/release-one-image-by-branch.groovy
- pipelines/tcms-daily-reports.groovy
Signed-off-by: purelind <purelind@gmail.com>
> use new cluster

- pipelines/release-all-binary-by-branch.groovy
- pipelines/release-all-images-by-branch.groovy
Signed-off-by: purelind <purelind@gmail.com>
> adjsut cluster

- atom-jobs/build-common.groovy
* set pull image policy to avoid inconsistencies in the runningtime of tidb-server and enterprise-plugin
> fix: set always pull image to true

- pipelines/hotfix-build-by-tag.groovy
update hotfix build pipeline
* support product for tidb / br / dumpling / dm / ticdc / tiflash / pd / tikv 
* support arm64 and amd64 build
* support community and enterprise build
* support pipeline debug mode
> update hotfix build

- tipipeline/common.groovy
* workaround for this jenkins blue-ocean display issue https://issues.jenkins.io/browse/JENKINS-53649
> fix: workaround for blueocean url display issue

- pipelines/hotfix-build-by-tag.groovy
* support push image to gcr and dockerhub
* support build multi-arch image
> hotfix build support gcr

- atom-jobs/docker-common-check.groovy
- atom-jobs/docker-common.groovy
* add retry for download dockerfile from github
> docker-common: add retry to download dockerfile from github

- atom-jobs/docker-common-check.groovy
- atom-jobs/docker-common.groovy
* mv original dockerfile to bak file, not affect download file from github
> docker-common(fix): remove original dockerfile at first

- atom-jobs/build-common.groovy
* upgrade go 1.18 minor version to 1.18.5
> base image: upgrade go to 1.18.5

- pipelines/hotfix-build-by-tag.groovy
> bugfix: use string rather than choise in argument

- pipelines/hotfix-build-by-tag.groovy
Automate enterprise plugin hash
> Automate plugin

- pipelines/hotfix-build-by-tag.groovy
* use regex to match release branch from hotifix tag
* fix parallel build bug: not build amd64 tidb binary
* get plugin hash directly from api
> fix parallel bug and plugin branch reg match

- pipelines/hotfix-build-by-tag.groovy
> allow push enterprise image to dockerhub

- atom-jobs/build-common.groovy
* fix arm64 not use currect go version
> fix build arm go version

- atom-jobs/build-common.groovy
- pipelines/hotfix-build-by-tag.groovy
this PR delete the git workspace and checkout all file out to avoid submodule un-clean
> fix git workspace clean

- pipelines/release-all-images-by-branch.groovy
> add release 6.4 for multibranch

- pipelines/release-all-images-by-branch.groovy
> latest version to be 6.5.0-alpha

- atom-jobs/build-common.groovy
> upgrade go1.19 to go 1.19.2

- atom-jobs/build-common.groovy
> fix: special treatment for nightly

- pipelines/release-all-images-by-branch.groovy
> fix: add release-6.5 to daily build

- pipelines/release-all-images-by-branch.groovy
> chore: bump nightly to v6.6.0-alpha

- atom-jobs/build-common.groovy
> fix(build-common): dm monitor grafana file patch change

- atom-jobs/build-common.groovy
specify a container to fix missing curl error
replay link https://cd.pingcap.net/job/build-common/173814/console
> fix: fix missing curl to check cached file

- atom-jobs/build-common.groovy
Regular updates to go version: upgrade go1.19 from 1.19.3 to 1.19.5.
> feat(build-common): upgrade go1.19 to 1.19.5

- pipelines/release-all-images-by-branch.groovy
> feat: nightly use rocky

- atom-jobs/build-common.groovy
Regular updates to go version: upgrade go1.18 from 1.18.5 to 1.18.10.
> feat: upgrade go1.18 to 1.18.10

- tipipeline/common.groovy
> fix: update api endpoint

- atom-jobs/atom-build.groovy
- atom-jobs/atom-common.groovy
- atom-jobs/atom-cyclo.groovy
- atom-jobs/atom-gosec.groovy
- atom-jobs/atom-lint.groovy
- atom-jobs/atom-ut-codecov.groovy
- atom-jobs/atom-ut.groovy
- atom-jobs/cache-code.groovy
- pipelines/hotfix-build-by-tag.groovy
- tipipeline/common.groovy
> chore: update nfs

- tipipeline/checkers/common-check.groovy
- tipipeline/common.groovy
* use high performance node to run pod
* add retry to download code
> fix: update pod nodeselector

- atom-jobs/atom-build.groovy
- atom-jobs/atom-common.groovy
- atom-jobs/atom-cyclo.groovy
- atom-jobs/atom-gosec.groovy
- atom-jobs/atom-jenkins-it-trigger.groovy
- atom-jobs/atom-lint.groovy
- atom-jobs/atom-tcms.groovy
- atom-jobs/atom-ut-codecov.groovy
- atom-jobs/atom-ut.groovy
- atom-jobs/cache-code.groovy
- pipelines/check-all-images-by-trivy.groovy
- pipelines/hotfix-build-by-tag.groovy
- pipelines/release-all-binary-by-branch.groovy
- pipelines/release-all-images-by-branch.groovy
- pipelines/release-one-image-by-branch.groovy
- pipelines/tcms-daily-reports.groovy
- tipipeline/common.groovy
Add nodeSelector to use linux/amd64 node.
> chore: add nodeselector to use linux/amd64 node
